baseURL = 'https://blog.hugosset.xyz/'
languageCode = 'en-us'
theme = 'etch'
title = 'blog.hugosset.xyz'

enableGitInfo = true
enableRobotsTXT = true
enableEmoji = true

[markup]
  [markup.highlight]
  style = 'xcode-dark'
  guessSyntax = true
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true

[params]
  description = "Personal blog of Hugo Sulaiman Setiawan"
  copyright = "Copyright © 2023 Hugo Sulaiman Setiawan"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[security]
  enableInlineShortcodes = true
